            - name: TypeScript Build
  # You may pin to the exact commit or the version.
  # uses: alexthemaster/action-build-typescript@d0935101a24426420d5bd5692a4cf16631cd6605
  uses: alexthemaster/action-build-typescript@v1.3.1
  with:
    # Whether or not to push the compiled code to a different branch
    pushToBranch: true # optional
    # The name of the branch the action should push the compiled code
    branch: 'website' # optional, default is dist
    # Your GitHub secret token
    githubToken: ${{ secrets.GITHUB_TOKEN }} # optional
          
